'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { getPaymentInformation } from '@/ai/flows/payment-information-retrieval';
import { FadeIn } from '../fade-in';
import { Loader2 } from 'lucide-react';

const InvoiceHistorySection = () => {
  const [invoiceInfo, setInvoiceInfo] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchInvoiceInfo = async () => {
    setIsLoading(true);
    setError(null);
    setInvoiceInfo(null);
    try {
      const result = await getPaymentInformation({ query: 'Show me my recent payment information' });
      setInvoiceInfo(result.paymentInformation);
    } catch (e) {
      console.error(e);
      setError('Failed to retrieve payment information. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <section id="invoices" className="py-16 md:py-24">
      <div className="container mx-auto px-4 text-center">
        <FadeIn>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">Payment Information</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-12">
            Retrieve your recent payment details and account status.
          </p>
        </FadeIn>
        <div id="invoice-history" className="max-w-2xl mx-auto">
          {!invoiceInfo && !isLoading && !error && (
            <FadeIn>
              <Card className="p-6 text-center">
                <CardContent className="pt-6">
                  <p className="text-muted-foreground mb-4">Click the button to fetch your latest payment information.</p>
                  <Button onClick={fetchInvoiceInfo} className="btn-primary rounded-full">
                    Get Payment Info
                  </Button>
                </CardContent>
              </Card>
            </FadeIn>
          )}

          {isLoading && (
            <Card className="p-6 text-center">
              <CardContent className="pt-6 flex items-center justify-center">
                <Loader2 className="mr-2 h-6 w-6 animate-spin" />
                <p className="text-muted-foreground">Loading information...</p>
              </CardContent>
            </Card>
          )}

          {error && (
            <Card className="p-6 text-center border-destructive">
                <CardContent className="pt-6">
                    <p className="text-destructive-foreground">{error}</p>
                    <Button onClick={fetchInvoiceInfo} variant="destructive" className="mt-4">Try Again</Button>
                </CardContent>
            </Card>
          )}

          {invoiceInfo && (
            <FadeIn>
              <Card className="text-left">
                <CardHeader>
                  <CardTitle>Your Payment Details</CardTitle>
                  <CardDescription>Generated by SarAfra Assist AI</CardDescription>
                </CardHeader>
                <CardContent>
                  <pre className="text-sm text-foreground whitespace-pre-wrap font-body">{invoiceInfo}</pre>
                  <Button onClick={fetchInvoiceInfo} className="btn-primary rounded-full mt-6">
                    Fetch Again
                  </Button>
                </CardContent>
              </Card>
            </FadeIn>
          )}
        </div>
      </div>
    </section>
  );
};

export default InvoiceHistorySection;
